### PR TITLE
Salome dockerfile used in FT2

### PR DESCRIPTION
**Pull request by victorsndvg**
Salome dockerfile used in FT2

### CODE REVIEW

**Comment by Trophime** [comment]
@victorsndvg just a quick comment regarding the script to launch salome.
As Salome would also be run in script mode (referred to as TUI in Salome dialect) it will be great to be able to pass some arguments in the script for FT2...

**Comment by victorsndvg** [comment]
Ok @Trophime , can you give me an example command line to see how you want to launch salome?

**Comment by Trophime** [comment]
For instance I use: 
```~/salome_with_paraview-7.5.1-2/salome_appli_7.5.1/runAppli -t create_Helix.py args:HR-20_H1.yaml,--splitxao```
This is the "old way" to launch salome. Now you can replace ```runAppli``` by ```salome```

But more simply to replay a TUI python script (from python dump) you would use:
```salome -t dump_python.py``` 
where ```-t``` stands for no graphics.

**Comment by victorsndvg** [comment]
hi @Trophime ,

we have enabled 2 different commands. One to run the gui (`$ salome_gui`) and other to run the tui (`$ salome_tui`).

Also the [wiki](https://github.com/MSO4SC/feelpp/wiki/Finis-Terrae-II:-Launch-Salome) has been updated.

Let me know if this changes fits with your needs

**Comment by emepetres** [comment]
so @Trophime , @victorsndvg , can I merge the pull request?

**Comment by victorsndvg** [comment]
:+1: 
For me it's Ok. Nothing has changed in these files since I did the PR

**Pull request merged**
